status = [
    "test (msrv)",
    "test (stable)",
    "test (beta)",
    "test (nightly)",
    "test (macos)",
    "test (win-gnu)",
    "test (win-msvc)",
    "rustfmt",
    "clippy",
    "licenses_and_advisories (advisories)",
    "licenses_and_advisories (bans licenses sources)",
    "msrv"
]
