[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Zlib",
    "BSD-3-Clause"
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = [
    # Potential segfault in the time crate
    # NB: has been fixed in time >=0.2.23, however waiting on chrono crate to update
    # chrono PR: https://github.com/chronotope/chrono/pull/578
    "RUSTSEC-2020-0071",
    # Potential segfault in localtime_r invocations, see 0071
    "RUSTSEC-2020-0159",
]
