name: "ci-build-release-binaries"

on:
  release:
    types: [created]

jobs:
  build_binaries:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive_ext: tgz

          - target: x86_64-apple-darwin
            os: macos-latest
            archive_ext: tgz

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive_ext: zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout_tagged_commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: set_archive_name
        shell: bash
        run: echo "archive=cargo-msrv-${{ matrix.target }}-${{ github.event.release.tag_name }}.${{ matrix.archive_ext }}" >> $GITHUB_OUTPUT

      - name: set_subfolder
        shell: bash
        run: echo "subfolder=cargo-msrv-${{ matrix.target }}-${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: show_outputs
        shell: bash
        run: |
          echo "Archive: '${{ steps.create-archive-name.outputs.archive }}'"
          echo "Subfolder: '${{ steps.create-archive-name.outputs.subfolder }}'"
      
      - name: create_pkg_subfolder
        shell: bash
        run: mkdir ${{ steps.create-archive-name.outputs.subfolder }}
            
      - name: copy_files_to_pkg_subfolder
        shell: bash
        run: |
          cp LICENSE-APACHE ${{ steps.create-archive-name.outputs.subfolder }}
          cp LICENSE-MIT ${{ steps.create-archive-name.outputs.subfolder }}
          cp README.md ${{ steps.create-archive-name.outputs.subfolder }}
      
      - name: install_rust
        uses: dtolnay/rust-toolchain@stable

      - name: build_${{ matrix.target }}_release_binary
        shell: bash
        run: cargo build --target=${{ matrix.target }} --release

      - name: install_cargo_about
        shell: bash
        run: cargo install cargo-about

      - name: generate_dep_licenses_file
        shell: bash
        run: cargo about generate --output-file "${{ steps.create-archive-name.outputs.subfolder }}/third-party-licenses.html" about.hbs

      - name: pack_archive_macos
        if: matrix.os == 'macos-latest'
        shell: bash
        run:
          cp  ./target/${{ matrix.target }}/release/cargo-msrv ${{ steps.create-archive-name.outputs.subfolder }}
          gtar --create --gzip --file=${{ steps.create-archive-name.outputs.archive }} ${{ steps.create-archive-name.outputs.subfolder }}

      - name: pack_archive_linux
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/cargo-msrv ${{ steps.create-archive-name.outputs.subfolder }}
          tar --create --gzip --file=${{ steps.create-archive-name.outputs.archive }} ${{ steps.create-archive-name.outputs.subfolder }}

      - name: pack_archive_windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/cargo-msrv.exe ./${{ steps.create-archive-name.outputs.subfolder }}
          7z a -tzip ${{ steps.create-archive-name.outputs.archive }} ${{ steps.create-archive-name.outputs.subfolder }}

      - name: upload_artifact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.create-archive-name.outputs.archive }}
          asset_name: ${{ steps.create-archive-name.outputs.archive }}
          asset_content_type: application/gzip
