on:
  pull_request:

name: Code Coverage

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v3

      - name: install_rust_nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: run_code_coverage
        uses: actions-rs/tarpaulin@v0.1.0
        with:
          args: "--all-features --ignore-tests --frozen --timeout 1500 -- --test-threads=1"

      - name: upload_code_coverage
        uses: codecov/codecov-action@v3
